import { v2 as cloudinary } from "cloudinary";
import discoverVideoModel from "../models/discoverVideoModel.js";
import productModel from "../models/productModel.js";

// Ensure Cloudinary is configured
const initCloudinary = () => {
    cloudinary.config({
        cloud_name: process.env.CLOUDINARY_NAME,
        api_key: process.env.CLOUDINARY_API_KEY,
        api_secret: process.env.CLOUDINARY_SECRET_KEY
    });
};

// Upload Video
const uploadVideo = async (req, res) => {
    try {
        initCloudinary();
        const { productId, title, description } = req.body;
        const videoFile = req.file;

        if (!videoFile) {
            return res.json({ success: false, message: "No video file provided." });
        }

        // Verify product exists
        const product = await productModel.findById(productId);
        if (!product) {
            return res.json({ success: false, message: "Associated product not found." });
        }

        // Upload to Cloudinary with compression and thumbnail generation
        const result = await cloudinary.uploader.upload(videoFile.path, {
            resource_type: "video",
            folder: "discover_videos",
            eager: [
                { width: 720, crop: "limit", format: "mp4", video_codec: "auto", quality: "auto" }
            ],
            eager_async: false // wait for eager transformation
        });

        // The optimized URL is in eager[0].secure_url
        // The thumbnail URL is generated by replacing extension with .jpg
        const optimizedUrl = result.eager && result.eager[0] ? result.eager[0].secure_url : result.secure_url;
        const thumbnailUrl = optimizedUrl.replace(/\.(mp4|mov|webm)$/i, '.jpg');

        const sellerId = req.adminId ? req.adminId : 'admin';

        const newVideo = new discoverVideoModel({
            productId,
            videoUrl: optimizedUrl,
            thumbnailUrl,
            publicId: result.public_id,
            title,
            description,
            sellerId
        });

        await newVideo.save();
        res.json({ success: true, message: "Video uploaded and optimized successfully.", video: newVideo });

    } catch (error) {
        console.error("Video Upload Error:", error);
        res.json({ success: false, message: error.message });
    }
};

// Get Feed (Lazy loading with pagination)
const getVideosFeed = async (req, res) => {
    try {
        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 5;
        const skip = (page - 1) * limit;

        const videos = await discoverVideoModel.find({ status: 'published' })
            .sort({ createdAt: -1 })
            .skip(skip)
            .limit(limit)
            .populate({
                path: 'productId',
                select: 'name price image sizes category subCategory _id storeName'
            });

        // Filter out videos whose products were deleted
        const validVideos = videos.filter(v => v.productId !== null);

        res.json({ success: true, videos: validVideos });

    } catch (error) {
        console.error("Get Feed Error:", error);
        res.json({ success: false, message: error.message });
    }
};

// Admin/Seller get their videos
const getMyVideos = async (req, res) => {
    try {
        let query = {};
        if (req.role === 'seller') {
            const sellerId = req.adminId;
            query = { sellerId };
        }
        
        const videos = await discoverVideoModel.find(query)
            .sort({ createdAt: -1 })
            .populate('productId', 'name image');

        res.json({ success: true, videos });
    } catch (error) {
        console.error("Get My Videos Error:", error);
        res.json({ success: false, message: error.message });
    }
};

// Delete Video
const deleteVideo = async (req, res) => {
    try {
        initCloudinary();
        const { id } = req.body;

        const video = await discoverVideoModel.findById(id);
        if (!video) {
            return res.json({ success: false, message: "Video not found." });
        }

        // Delete from Cloudinary
        await cloudinary.uploader.destroy(video.publicId, { resource_type: 'video' });

        // Delete from MongoDB
        await discoverVideoModel.findByIdAndDelete(id);

        res.json({ success: true, message: "Video deleted successfully." });

    } catch (error) {
        console.error("Delete Video Error:", error);
        res.json({ success: false, message: error.message });
    }
};

// Update Metrics (Views/Likes/Clicks)
const updateMetrics = async (req, res) => {
    try {
        const { id, metric } = req.body; // metric = 'views', 'likes', or 'clicks'
        
        if (!['views', 'likes', 'clicks'].includes(metric)) {
            return res.json({ success: false, message: "Invalid metric type." });
        }

        await discoverVideoModel.findByIdAndUpdate(id, {
            $inc: { [`metrics.${metric}`]: 1 }
        });

        res.json({ success: true });
    } catch (error) {
        console.error("Update Metrics Error:", error);
        res.json({ success: false, message: error.message });
    }
};

export { uploadVideo, getVideosFeed, getMyVideos, deleteVideo, updateMetrics };
